x-environment: &environment
  environment:
    - APP_NAME="HomeOrganizer"
    - DB_DATABASE=homeorganizerdb
    - DB_USERNAME=homeorganizerdb_user
    - DB_PASSWORD=homeorganizerDbPassword
    - PG_DB_DATABASE=homeorganizerdb_pg
    - PG_DB_DATABASE_TEST=homeorganizerdb_pg_testing
    - PG_DB_USERNAME=homeorganizerdb_pg_user
    - PG_DB_PASSWORD=homeorganizerDbPgPassword
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=superSecureRootPass

x-common-attributes: &common-attributes
  init: true
  restart: unless-stopped
  networks:
    - homeorganizer

services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    image: 'homeorganizer'
    <<: [*common-attributes, *environment]
    ports:
      - '80:80'
      - '443:443'
      - '9001:9001'
      - '5173:5173'
      - '8080:8080'
      - '6001:6001'
    command: /bin/bash
    volumes:
      - './laravel:/var/www/html'
    depends_on:
      rds:
        condition: service_started
      postgres:
        condition: service_healthy

  rds:
    image: 'mariadb:11.5.2'
    <<: [*common-attributes]
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "yqQ6yI6QvTO5"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: homeorganizerdb
      MYSQL_USER: homeorganizerdb_user
      MYSQL_PASSWORD: homeorganizerDbPassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'homeorganizer-rds-db:/var/lib/mysql'
      - './_docker/rds/create-database.sh:/docker-entrypoint-initdb.d/10-create-database.sh'
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      retries: 3
      timeout: 5s

  postgres:
    image: 'postgres:16-alpine'
    <<: [*common-attributes]
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecureRootPass
      POSTGRES_DB: homeorganizerdb_pg
      PG_DB_DATABASE: homeorganizerdb_pg
      PG_DB_DATABASE_TEST: homeorganizerdb_pg_testing
      PG_DB_USERNAME: homeorganizerdb_pg_user
      PG_DB_PASSWORD: homeorganizerDbPgPassword
    volumes:
      - 'homeorganizer-postgres:/var/lib/postgresql/data'
      - './_docker/postgres/init:/docker-entrypoint-initdb.d'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\" -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: 'redis:alpine'
    <<: [*common-attributes]
    ports:
      - '6379:6379'
    volumes:
      - 'homeorganizer-redis:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  redisinsights:
    image: 'redislabs/redisinsight:latest'
    <<: [*common-attributes]
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - 'homeorganizer-redis-insight-data:/db'

  mailpit:
    image: 'axllent/mailpit:latest'
    <<: [*common-attributes]
    ports:
      - '1025:1025'
      - '8025:8025'

  phpmyadmin:
    image: 'phpmyadmin:5.2.1'
    <<: [*common-attributes]
    ports:
      - '8081:80'
    environment:
      PMA_HOST: rds
      PMA_PORT: 3306
      PMA_USER: homeorganizerdb_user
      PMA_PASSWORD: homeorganizerDbPassword
    depends_on:
      rds:
        condition: service_started

volumes:
  homeorganizer-rds-db:
  homeorganizer-postgres:
  homeorganizer-redis:
  homeorganizer-redis-insight-data: { }

networks:
  homeorganizer:
    driver: bridge
