x-common-env: &common-env
  APP_NAME: HomeOrganizer
  DB_DATABASE: homeorganizerdb
  DB_USERNAME: homeorganizerdb_user
  DB_PASSWORD: homeorganizerDbPassword
  PG_DB_DATABASE: homeorganizerdb_pg
  PG_DB_DATABASE_TEST: homeorganizerdb_pg_testing
  PG_DB_USERNAME: homeorganizerdb_pg_user
  PG_DB_PASSWORD: homeorganizerDbPgPassword
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: superSecureRootPass

x-common-attributes: &common-attributes
  init: true
  restart: unless-stopped
  networks:
    - homeorganizer

services:
  backend:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
      target: backend
    image: 'homeorganizer-backend'
    <<: *common-attributes
    environment:
      <<: *common-env
    ports:
      - '6001:6001'
      - '8080:8080'
      - '9001:9001'
    volumes:
      - './backend:/var/www/html'
      - 'homeorganizer-nginx-ssl:/etc/nginx/ssl'
    depends_on:
      rds:
        condition: service_started
      postgres:
        condition: service_healthy

  proxy-server:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
      target: proxy
    image: 'homeorganizer-proxy'
    <<: *common-attributes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './backend:/var/www/html:ro'
      - './_docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './_docker/nginx/conf/:/etc/nginx/conf.d:ro'
      - './_docker/nginx/server/server.conf:/etc/nginx/sites-available/default:ro'
      - './_docker/nginx/start-container.sh:/start-container.sh:ro'
      - 'homeorganizer-nginx-ssl:/etc/nginx/ssl:ro'
    command: bash /start-container.sh
    depends_on:
      - backend

  node:
    image: 'node:20.11.1'
    <<: *common-attributes
    working_dir: /var/www/html
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      NODE_OPTIONS: "--dns-result-order=ipv4first"
      NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/"
      YARN_CACHE_FOLDER: "/usr/local/share/.cache/yarn"
    ports:
      - '5173:5173'
    volumes:
      - './backend:/var/www/html'
      - './_docker/node/start-container.sh:/start-container.sh:ro'
      - 'homeorganizer-nginx-ssl:/etc/nginx/ssl:ro'
      - 'homeorganizer-yarn-cache:/usr/local/share/.cache/yarn'
    command: sh /start-container.sh
    depends_on:
      - backend

  rds:
    image: 'mariadb:11.5.2'
    <<: [*common-attributes]
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "yqQ6yI6QvTO5"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: homeorganizerdb
      MYSQL_USER: homeorganizerdb_user
      MYSQL_PASSWORD: homeorganizerDbPassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'homeorganizer-rds-db:/var/lib/mysql'
      - './_docker/rds/create-database.sh:/docker-entrypoint-initdb.d/10-create-database.sh'
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      retries: 3
      timeout: 5s

  postgres:
    image: 'postgres:16-alpine'
    <<: [*common-attributes]
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecureRootPass
      POSTGRES_DB: homeorganizerdb_pg
      PG_DB_DATABASE: homeorganizerdb_pg
      PG_DB_DATABASE_TEST: homeorganizerdb_pg_testing
      PG_DB_USERNAME: homeorganizerdb_pg_user
      PG_DB_PASSWORD: homeorganizerDbPgPassword
    volumes:
      - 'homeorganizer-postgres:/var/lib/postgresql/data'
      - './_docker/postgres/init:/docker-entrypoint-initdb.d'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\" -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: 'redis:alpine'
    <<: [*common-attributes]
    ports:
      - '6379:6379'
    volumes:
      - 'homeorganizer-redis:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  redisinsights:
    image: 'redislabs/redisinsight:latest'
    <<: [*common-attributes]
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - 'homeorganizer-redis-insight-data:/db'

  mailpit:
    image: 'axllent/mailpit:latest'
    <<: [*common-attributes]
    ports:
      - '1025:1025'
      - '8025:8025'

  phpmyadmin:
    image: 'phpmyadmin:5.2.1'
    <<: [*common-attributes]
    ports:
      - '8081:80'
    environment:
      PMA_HOST: rds
      PMA_PORT: 3306
      PMA_USER: homeorganizerdb_user
      PMA_PASSWORD: homeorganizerDbPassword
    depends_on:
      rds:
        condition: service_started

volumes:
  homeorganizer-rds-db:
  homeorganizer-postgres:
  homeorganizer-redis:
  homeorganizer-redis-insight-data: { }
  homeorganizer-nginx-ssl:
  homeorganizer-yarn-cache:

networks:
  homeorganizer:
    driver: bridge
