/**
 * StepOrchestrator
 *
 * Central coordinator for step-based behavior.
 * Uses declarative configuration instead of step classes.
 *
 * Event-driven architecture:
 * - Emits STEP_INFO_CHANGED events via EventBus when step state changes
 * - Subscribe to STEP_INFO_CHANGED via EventBus for step updates
 */

import type {
  ClickContext,
  StepInfo,
  ManagerInstances,
  StepConfiguration,
  StepState,
} from '@/Components/Grid/types/orchestration';
import { STEPS, createStep } from '@/Components/Grid/types/steps';
import { SHAPE_COLORS } from '@/Components/Grid/types/constants';
import { StepHandlers } from '@/Components/Grid/steps/StepHandlers';
import type { EventBus } from '@/Components/Grid/core/events';

export class StepOrchestrator {
  private stepConfigs: Map<number, StepConfiguration> = new Map();
  private currentStepConfig: StepConfiguration;
  private currentState: StepState;
  private managers: ManagerInstances;
  private eventBus: EventBus | null = null;

  constructor(managers: ManagerInstances) {
    this.managers = managers;

    // Configure all steps (declarative!)
    this.configureSteps();

    // Start with Step 1
    this.currentStepConfig = this.stepConfigs.get(1)!;
    this.currentState = {
      shapeIds: [],
      selectedShapeId: null,
      primaryShapeId: null,
      isSaved: false,
    };

    this.enterStep(this.currentStepConfig);
  }

  /**
   * Centralized step configuration
   */
  private configureSteps(): void {
    // Step 1: Home Area
    // layerId will be auto-generated by LayerManager based on step.id
    this.stepConfigs.set(1, {
      step: STEPS.HOME_AREA,
      layerId: `layer_${STEPS.HOME_AREA.id}`, // e.g., "layer_home_area"
      shapeType: 'rectangle',
      shapeDefaults: {
        label: 'Home Area',
        fill: SHAPE_COLORS.HOME_AREA_FILL,
        stroke: SHAPE_COLORS.HOME_AREA_STROKE,
      },
      rules: {
        maxShapes: 1,              // Only ONE home area
        requiresSelection: false,
        canDelete: true,
      },
    });

    // Future: Step 2, 3, etc. will be added here or dynamically
  }

  /**
   * Enter a step - orchestrator controls layer creation
   */
  private enterStep(config: StepConfiguration): void {
    // Create layer for this step
    // For child steps, pass parentLayerId and areaId for proper hierarchy
    const parentLayerId = config.parentContext?.parentLayerId || null;
    const areaId = config.parentContext?.parentAreaId || undefined;
    const layer = this.managers.layerManager.createLayer(config.step, parentLayerId, areaId);

    // Update config.layerId to match the actual created layer ID
    config.layerId = layer.id;

    // Handle parent context if this is a child area step
    if (config.parentContext) {
      // Lock all parent layers (Step 1 layers when entering Step 2)
      // This uses the layer locking system instead of per-shape manipulation
      this.managers.layerManager.lockAllLayersExcept(layer.id, this.managers.shapeManager);

      // Set grid clipping (visual effect only)
      // Note: Transform bounds are now handled by BoundsService via live parent queries
      this.managers.gridManager.setClipBounds(config.parentContext.parentBounds);
    }

    // Emit to UI
    this.notifyStepChange();
  }

  /**
   * Exit a step - orchestrator controls cleanup
   */
  private exitStep(config: StepConfiguration): void {
    // Use SelectionManager to deselect
    this.managers.selectionManager.deselect();

    // Handle parent context cleanup if this was a child area step
    if (config.parentContext) {
      // Unlock all previously locked layers (restore Step 1 interactivity)
      this.managers.layerManager.unlockAllLayers(this.managers.shapeManager);

      // Reset parent visual state if it was selected
      this.managers.selectionManager.resetParentVisual(config.parentContext.parentShapeId);

      // Clear grid clipping (visual effect only)
      // Note: Transform bounds are now handled by BoundsService via live parent queries
      this.managers.gridManager.clearClipBounds();
    }

    // Note: Layer visibility/opacity is managed by LayerManager.setCurrentLayer()
  }

  /**
   * Handle click events from EventBus - receives pre-extracted data instead of raw Konva event
   */
  handleClickFromEvent(
    worldPosition: { x: number; y: number },
    target: 'canvas' | 'shape' | 'other',
    shapeId?: string
  ): void {
    const context: ClickContext = {
      target,
      position: worldPosition,
      shapeId,
      event: undefined, // No raw event in event-driven approach
    };

    // Delegate to step handler with configuration
    StepHandlers.handleClick(
      context,
      this.currentStepConfig,
      this.currentState,
      this.managers
    );

    this.notifyStepChange();
  }

  /**
   * Delete shape - orchestrator manages state
   */
  private deleteShape(shapeId: string): void {
    const result = StepHandlers.deleteShape(
      shapeId,
      this.currentStepConfig,
      this.currentState,
      this.managers
    );

    // Reset saved state when shape is deleted
    this.currentState.isSaved = false;

    // Track if we deleted the last child for potential transition on save
    if (result.deletedLastChild) {
      this.currentState.deletedLastChild = true;
    }

    this.notifyStepChange();
  }

  /**
   * Save current step
   */
  private async saveStep(): Promise<void> {
    await StepHandlers.saveStep(
      this.currentStepConfig,
      this.currentState,
      this.managers
    );

    // If we're in a child step and deleted all children, transition back to parent step
    if (this.currentState.deletedLastChild && this.currentStepConfig.parentContext) {
      await this.transitionToParentStep();
      return;
    }

    this.notifyStepChange();
  }

  /**
   * Transition back to parent step (Step 1)
   * Called when all child shapes are deleted and saved
   */
  private async transitionToParentStep(): Promise<void> {
    if (!this.currentStepConfig.parentContext) return;

    // Get the parent config (Step 1)
    const parentConfig = this.stepConfigs.get(1);
    if (!parentConfig) return;

    // Get the parent layer to restore
    const parentLayer = this.managers.layerManager.getLayer(this.currentStepConfig.parentContext.parentLayerId);

    // Exit current (child) step
    this.exitStep(this.currentStepConfig);

    // Switch to parent step
    this.currentStepConfig = parentConfig;

    // Restore state from parent layer
    this.currentState = {
      shapeIds: parentLayer?.shapeIds || [],
      selectedShapeId: null,
      primaryShapeId: parentLayer?.primaryShapeId || null,
      isSaved: true, // Parent was saved
    };

    // Set the parent layer as current (this updates opacity)
    if (parentLayer) {
      this.managers.layerManager.setCurrentLayer(parentLayer.id);
    }

    // Auto-select the primary shape
    if (this.currentState.primaryShapeId) {
      this.managers.selectionManager.select(
        this.currentState.primaryShapeId,
        parentConfig.layerId
      );
      this.currentState.selectedShapeId = this.currentState.primaryShapeId;
    }

    this.notifyStepChange();
  }

  /**
   * Load saved home area from storage
   */
  async loadHomeArea(): Promise<boolean> {
    const loaded = await StepHandlers.loadHomeArea(
      this.currentStepConfig,
      this.currentState,
      this.managers
    );

    this.notifyStepChange();
    return loaded;
  }

  /**
   * Load saved child areas from storage for current parent
   */
  async loadChildAreas(): Promise<boolean> {
    const loaded = await StepHandlers.loadChildAreas(
      this.currentStepConfig,
      this.currentState,
      this.managers
    );

    this.notifyStepChange();
    return loaded;
  }

  /**
   * Restore full state from persistence
   * This loads home area, checks saved step, and transitions to that step
   */
  async restoreState(): Promise<boolean> {
    const pm = this.managers.persistenceManager;
    if (!pm) {
      console.error('StepOrchestrator: PersistenceManager not available');
      return false;
    }

    // Load saved data to check if there's anything to restore
    const savedData = await pm.getCurrentData();
    if (!savedData) {
      console.log('StepOrchestrator: No saved state to restore');
      return false;
    }

    // CRITICAL: Restore area hierarchy FIRST before loading shapes
    // This ensures that when shapes are loaded with preserved IDs,
    // the area-to-shape mappings are already valid
    if (savedData.areaHierarchy && savedData.areaHierarchy.rootAreaId) {
      console.log('StepOrchestrator: Restoring area hierarchy...');
      // Legacy: Use AreaManager for deserialization during migration
      // TODO: Remove after Phase E migration is complete
      this.managers.areaManager.deserialize(
        savedData.areaHierarchy,
        this.managers.shapeManager
      );
      console.log('StepOrchestrator: Area hierarchy restored', savedData.areaHierarchy);
    }

    // Now load the home area shapes (Step 1)
    const homeLoaded = await this.loadHomeArea();
    if (!homeLoaded) {
      console.log('StepOrchestrator: No saved home area to restore');
      return false;
    }

    // Check what step we were on
    const savedStep = await pm.getSavedStep();
    console.log('StepOrchestrator: Saved step was', savedStep);

    // If saved step was 2+, transition to that step
    if (savedStep >= 2 && this.currentState.primaryShapeId) {
      // Mark Step 1 as saved (it was already saved)
      this.currentState.isSaved = true;

      // Transition to Step 2 - this will also load child areas
      await this.createChildAreaStep();

      console.log('StepOrchestrator: Restored to Step', savedStep);
    }

    this.notifyStepChange();
    return true;
  }

  /**
   * Transition to next step
   */
  transitionToNextStep(): void {
    const nextOrder = this.currentStepConfig.step.order + 1;

    // Special handling for Step 1 -> Step 2 (child area creation)
    if (this.currentStepConfig.step.order === 1 && nextOrder === 2) {
      this.createChildAreaStep();
      return;
    }

    // Generic handling for future steps
    const nextConfig = this.stepConfigs.get(nextOrder);
    if (nextConfig) {
      this.exitStep(this.currentStepConfig);
      this.currentStepConfig = nextConfig;
      this.currentState = {
        shapeIds: [],
        selectedShapeId: null,
        primaryShapeId: null,
        isSaved: false,
      };
      this.enterStep(this.currentStepConfig);
    }
  }

  /**
   * Create child area step (Step 2) with parent context
   */
  private async createChildAreaStep(): Promise<void> {
    if (!this.currentState.primaryShapeId) {
      console.warn('Cannot create child area step: no primary shape');
      return;
    }

    const parentShape = this.managers.shapeManager.getShape(this.currentState.primaryShapeId);
    if (!parentShape) {
      console.warn('Cannot create child area step: parent shape not found');
      return;
    }

    // Use unified model: parentShapeId IS the area identifier
    // Legacy areaManager lookup is no longer needed
    const parentShapeId = this.currentState.primaryShapeId;

    // Verify the parent shape is an area shape
    const isArea = this.managers.shapeManager.isAreaShape(parentShapeId);
    if (!isArea) {
      // Fallback to legacy areaManager for backward compatibility
      // TODO: Remove after Phase E migration is complete
      const legacyAreaId = this.managers.areaManager?.findAreaByShapeId(parentShapeId);
      if (!legacyAreaId) {
        console.warn('Cannot create child area step: parent area not found');
        return;
      }
    }

    // In unified model, parentAreaId === parentShapeId
    const parentAreaId = parentShapeId;

    // Get the current layer ID (parent layer for the child step)
    const parentLayerId = this.currentStepConfig.layerId;

    // Configure Step 2 with parent context
    const step2Config: StepConfiguration = {
      step: createStep('AREA'),
      layerId: '', // Will be auto-generated by LayerManager
      shapeType: 'rectangle',
      shapeDefaults: {
        label: 'Area',
        fill: SHAPE_COLORS.AREA_FILL,
        stroke: SHAPE_COLORS.AREA_STROKE,
      },
      rules: {
        maxShapes: Infinity,
        requiresSelection: false,
        canDelete: true,
        requiresExplicitCreate: true,  // Must click "Create Area" before creating
      },
      parentContext: {
        parentAreaId,
        parentShapeId: this.currentState.primaryShapeId,
        parentLayerId,  // Pass parent layer for hierarchy
        parentBounds: {
          x: parentShape.x,
          y: parentShape.y,
          width: parentShape.width,
          height: parentShape.height,
        },
      },
    };

    // parentShapeId already set above from this.currentState.primaryShapeId

    this.stepConfigs.set(2, step2Config);
    this.exitStep(this.currentStepConfig);
    this.currentStepConfig = step2Config;
    this.currentState = {
      shapeIds: [],
      selectedShapeId: null,
      primaryShapeId: null,
      isSaved: false,
      parentAreaId,
      parentShapeId,
    };
    this.enterStep(step2Config);

    // Load any saved child areas for this parent
    await this.loadChildAreas();
  }

  /**
   * Get current step information for UI
   */
  getCurrentStepInfo(): StepInfo {
    // Get selected shape's current label/name
    let selectedShapeName: string | null = null;
    if (this.currentState.selectedShapeId) {
      const shape = this.managers.shapeManager.getShape(this.currentState.selectedShapeId);
      if (shape) {
        selectedShapeName = shape.label || '';
      }
    }

    return {
      step: this.currentStepConfig.step,
      description: StepHandlers.getDescription(
        this.currentStepConfig,
        this.currentState
      ),
      actions: StepHandlers.getToolbarActions(
        this.currentStepConfig,
        this.currentState,
        {
          onDelete: (shapeId) => this.deleteShape(shapeId),
          onSave: () => this.saveStep(),
          onNextStep: () => this.transitionToNextStep(),
          onEnableCreationMode: () => this.enableCreationMode(),
        }
      ),
      selectedShapeId: this.currentState.selectedShapeId,
      pendingAreaName: this.currentState.pendingAreaName || null,
      selectedShapeName,
      parentAreaId: this.currentState.parentAreaId || null,
    };
  }

  /**
   * Save area name (exposed to UI)
   */
  saveAreaName(areaId: string, name: string): void {
    StepHandlers.saveAreaName(
      areaId,
      name,
      this.currentState,
      this.managers
    );

    this.notifyStepChange();
  }

  /**
   * Save shape label/name (exposed to UI)
   */
  saveShapeLabel(shapeId: string, label: string): void {
    StepHandlers.saveShapeLabel(
      shapeId,
      label,
      this.currentState,
      this.managers
    );

    this.notifyStepChange();
  }

  /**
   * Enable creation mode (exposed to UI)
   * Used when "Create Area" button is clicked in steps that require explicit creation
   */
  enableCreationMode(): void {
    this.currentState.isCreationMode = true;
    this.notifyStepChange();
  }

  /**
   * Set the EventBus for event-driven communication
   */
  setEventBus(eventBus: EventBus): void {
    this.eventBus = eventBus;
  }

  /**
   * Notify listeners of step change via EventBus
   */
  private notifyStepChange(): void {
    if (this.eventBus) {
      this.eventBus.emit({
        type: 'STEP_INFO_CHANGED',
        payload: {
          stepInfo: this.getCurrentStepInfo(),
        },
      });
    }
  }

  // ==================== Pan Orchestration ====================

  /**
   * Handle pan-end orchestration flow
   * Called when a pan gesture completes (drag or middle-mouse release)
   *
   * Flow:
   * 1. Sync pan position to store (source of truth)
   * 2. Redraw grid with new pan offset
   * 3. Reinstantiate all shapes with fresh dragBoundFunc closures
   * 4. Set draggable state based on whether we're staying in pan mode
   *
   * @param panPosition - The new pan position from stage.position()
   * @param stayInPanMode - Whether pan mode should remain active after this gesture
   * @returns Promise that resolves when orchestration is complete
   */
  async handlePanEnd(panPosition: { x: number; y: number }, stayInPanMode: boolean): Promise<void> {
    console.log('[StepOrchestrator] Pan-end orchestration started', { panPosition, stayInPanMode });

    // 1. Sync pan position to store (source of truth)
    // ZoomManager handles updating both store and stage
    if (this.managers.zoomManager?.setPan) {
      this.managers.zoomManager.setPan(panPosition);
    }

    // 2. Redraw grid with new pan offset
    this.managers.gridManager.redrawGrid();

    // 3. Reinstantiate all shapes with fresh dragBoundFunc closures
    // Force draggable based on whether we're staying in pan mode
    await this.managers.shapeManager.reinstantiateShapes({ forceDraggable: !stayInPanMode });

    // 4. Reattach transformer to selected shape's new node instance
    // (reinstantiateShapes destroys old nodes, so transformer references are stale)
    this.reattachTransformerToSelectedShape();

    console.log('[StepOrchestrator] Pan-end orchestration complete');
  }

  /**
   * Handle pan-mode-exit orchestration flow
   * Called when pan mode is toggled OFF via button (not from drag gesture)
   *
   * Flow:
   * 1. Sync current pan position to store
   * 2. Redraw grid
   * 3. Reinstantiate shapes with draggable: true
   *
   * @param currentPanPosition - The current pan position from stage.position()
   * @returns Promise that resolves when orchestration is complete
   */
  async handlePanModeExit(currentPanPosition: { x: number; y: number }): Promise<void> {
    console.log('[StepOrchestrator] Pan-mode-exit orchestration started', { currentPanPosition });

    // 1. Sync pan position to store
    if (this.managers.zoomManager?.setPan) {
      this.managers.zoomManager.setPan(currentPanPosition);
    }

    // 2. Redraw grid
    this.managers.gridManager.redrawGrid();

    // 3. Reinstantiate shapes with draggable: true (exiting pan mode)
    await this.managers.shapeManager.reinstantiateShapes({ forceDraggable: true });

    // 4. Reattach transformer to selected shape's new node instance
    this.reattachTransformerToSelectedShape();

    console.log('[StepOrchestrator] Pan-mode-exit orchestration complete');
  }

  /**
   * Reattach transformer to the currently selected shape's new Konva node
   * Called after reinstantiateShapes to fix stale transformer references
   */
  private reattachTransformerToSelectedShape(): void {
    const { selectionManager, transformManager } = this.managers;

    if (!selectionManager || !transformManager) return;

    const selectedShapeId = selectionManager.getSelectedShapeId?.();
    if (!selectedShapeId) {
      // No shape selected, detach transformer
      transformManager.detach?.();
      return;
    }

    // Get the new node instance from ShapeManager
    const newNode = this.managers.shapeManager.getShapeNode(selectedShapeId);
    if (newNode) {
      console.log('[StepOrchestrator] Reattaching transformer to:', selectedShapeId);
      transformManager.attachTo(newNode);
    } else {
      console.warn('[StepOrchestrator] Could not find new node for shape:', selectedShapeId);
      transformManager.detach?.();
    }
  }
}
